/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.fero.ascent;


import com.jagrosh.jdautilities.commons.waiter.EventWaiter;
import com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeHttpContextFilter;
import me.duncte123.botcommons.messaging.EmbedUtils;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.requests.GatewayIntent;
import net.dv8tion.jda.api.utils.cache.CacheFlag;

import javax.security.auth.login.LoginException;
import java.util.EnumSet;

public class Bot {
    private Bot() throws LoginException {
        EmbedUtils.setEmbedBuilder(
                () -> new EmbedBuilder()
                        .setColor(0x3883d9)
        );

        EventWaiter waiter = new EventWaiter();
        JDABuilder jda =  JDABuilder.createDefault(
                Config.get("TOKEN"),
                GatewayIntent.GUILD_MEMBERS,
                GatewayIntent.GUILD_MESSAGES,
                GatewayIntent.GUILD_VOICE_STATES
                );

        jda.disableCache(EnumSet.of(
                CacheFlag.CLIENT_STATUS,
                CacheFlag.ACTIVITY,
                CacheFlag.EMOTE
        ));
        jda.enableCache(CacheFlag.VOICE_STATE);
//        jda.setActivity(Activity.listening("good music"));

        jda.addEventListeners(new Listener(waiter), waiter);
        jda.build();
        YoutubeHttpContextFilter.setPAPISID("gDIJZ27nqmM12kCm/Av7wzMjg-Dq5IMMG9");
        YoutubeHttpContextFilter.setPSID("GQjIL_RrduWKPps0jSZ8-hK4yj5Ua6zOkS0PPVmUKel3t-HKPM3NnFnpeo7VCMjro-W0hA.");

    }


    public static void main(String[] args) throws LoginException {
        new Bot();
    }


}
